config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SweetEnglish</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<a href="">
  <img src="https://res.cloudinary.com/dsgl1xjqn/image/upload/v1615843478/main-page_gtgydn.png" alt="">
</a>

app/views/pages/contact.html.erb
<div class="top-container">
  <img class="top-img" src="https://res.cloudinary.com/dsgl1xjqn/image/upload/v1616218476/cloud_nygohb.png" alt="">
  <h1>Hi, I am lena</h1>
  <p>a <span>pro</span>grammer</p>
  <img class="bottom-img" src="https://res.cloudinary.com/dsgl1xjqn/image/upload/v1616218476/cloud_nygohb.png" alt="">
  <img class="mountain" src="https://res.cloudinary.com/dsgl1xjqn/image/upload/v1616218476/mountain_sa8g1o.png" alt="">
</div>

<div class="middle-container">
  <div class="skill-top">
    <img class="palmtree" src="https://media.giphy.com/media/l0HlUZNyQ8jHgYedy/giphy.gif" alt="">
    <br>
    <br>
    <h3>Lena's Sweet English</h3>
    <p>I like to find a road for people. I like talking to them.
       I believe learning and self-belief create the diffierence.</p>
 </div>

  <div class="skill-bottom">
    <img class="yoga" src="https://media.giphy.com/media/3oKIPavRPgJYaNI97W/giphy.gif" alt="">
    <br>
    <br>
    <h3>Dedicated Ashtanga Yogi</h3>
    <p>I practiced Ashtanga yoga for 4 years. This is the process to find
      myself and bring back focus into my life.</p>
  </div>
</div>

<div class="bottom-container">
  <a href="">linkedin</a>
  <a href="">facebook</a>
  <a href="">Instagram</a>
  <div class="copyright">
    <p>2021 copyright @lena's sweet english</p>
  </div>
</div><a href="<%= about_path %>">

app/views/pages/home.html.erb
<h1>Welcome to Lena's Sweet English</h1>

app/views/shared/_navbar.html.erb
<div class="header">
  <%= link_to "home", root_path %>
  <%= link_to "about", about_path %>
  <%= link_to "contact", contact_path %>
</div>